TechPointProject/urls.py
from django.contrib import admin
from django.urls import path 
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),

]

mysite/urls.py
from django.urls import path, re_path
from mysite import views
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

# Links button addresses to django views

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('inventory/', views.inventory, name='inventory'),
    path('pantries/', views.pantries, name= 'pantries'),
    path('add/', views.add, name= 'add'),
    path('remove/', views.remove, name= 'remove'),
    path('about/', views.about, name='about'),
    re_path (r'^add_pantry$', add_pantry, name = 'add_pantry'),
    re_path (r'^edit_pantry/$', edit_pantry, name = 'edit_pantry'),
    re_path (r'^display_food$', display_food, name = 'display_food'),
    re_path (r'^add_food$', add_food, name = 'add_food'),
    re_path (r'^edit_food/(?P<pk>\d+)$', edit_food, name = 'edit_food'),
    re_path (r'^delete_food/(?P<pk>\d+)$', delete_food, name = 'delete_food'),
    re_path (r'^send_mail_form$', send_mail_form, name = 'send_mail_form'),
    re_path (r'^sign_up_form$', sign_up_form, name = 'sign_up_form'),
    re_path (r'^pantry_inventory/(?P<pantry_id>[0-9]+)$', pantry_inventory, name = 'pantry_inventory'),
    re_path (r'^add_hours$', add_hours, name = 'add_hours'),
    re_path (r'^edit_hours/(?P<pk>\d+)$', edit_hours, name = 'edit_hours'),
    re_path (r'^delete_hours/(?P<pk>\d+)$', delete_hours, name = 'delete_hours'),
    re_path (r'^add_need$', add_need, name = 'add_need'),
    re_path (r'^delete_need/(?P<pk>\d+)$', delete_need, name = 'delete_need'),
]

mysite/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from datetime import datetime, date, time
# Create your models here.


class Pantry(models.Model):

    name = models.CharField(max_length = 100)
    zipCode = models.CharField(max_length = 50)
    streetAdd1 = models.CharField(max_length = 100)
    streetAdd2 = models.CharField(max_length = 100, blank=True)
    city = models.CharField(max_length = 50)
    state = models.CharField(max_length = 2)
    distance = models.IntegerField(blank=True)


    #https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-phone-number-in-django-models
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list

    description = models.CharField(max_length = 1000, blank=True)

    websiteURL = models.CharField(max_length = 1000, blank=True)
    
    account = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    
    monday_start = models.TimeField(blank=True)
    monday_end = models.TimeField(blank=True)

    tuesday_start = models.TimeField(blank=True)
    tuesday_end = models.TimeField(blank=True)

    wednesday_start = models.TimeField(blank=True)
    wednesday_end = models.TimeField(blank=True)

    thursday_start = models.TimeField(blank=True)
    thursday_end = models.TimeField(blank=True)

    friday_start = models.TimeField(blank=True)
    friday_end = models.TimeField(blank=True)

    saturday_start = models.TimeField(blank=True)
    saturday_end = models.TimeField(blank=True)

    sunday_start = models.TimeField(blank=True)
    sunday_end = models.TimeField(blank=True)

    #users
    #notifiers
    #name
    #address
    #phone number
    #Description
    #hours
    #website URL
    #items in need of
    #food/inventory
    def __str__(self):
        return '{0}' .format(self.name)


    def getZipCode(self):
        return self.zipCode

class Food(models.Model): #name of table
    Name = models.CharField(max_length=100, blank = False) #item name?

    choices = (
        ('Stable', 'There is no excess or shortage of this food'),
        ('Excess', 'There is an excess of this food'),
        ('Shortage', 'There is a shortage of this food')
    )

    Status = models.CharField(max_length=100, choices=choices, blank = False) #stable/excess/shortage?
    Amount = models.IntegerField(blank = True) #optional exact amount

    Pantry = models.ForeignKey(Pantry, on_delete = models.CASCADE)

    def __str__(self):
        return 'Name : {0} Status : {1}' .format(self.Name, self.Status)


class Mail(models.Model):
    Subject = models.CharField(max_length=100, blank=False)
    Message = models.CharField(max_length=500, blank=False)
    def __str__(self):
        return 'Subject : {0} Message : {1}' .format(self.Subject, self.Message)
    
class Hours(models.Model):
    DAYS = [
        (1, ("Monday")),
        (2, ("Tuesday")),
        (3, ("Wednesday")),
      (4, ("Thursday")),
      (5, ("Friday")),
      (6, ("Saturday")),
      (7, ("Sunday")),
    ]
    dayNames = [
        ("Monday"),
        ("Tuesday"),
        ("Wednesday"),
        ("Thursday"),
        ("Friday"),
        ("Saturday"),
        ("Sunday")
    ]
    #https://stackoverflow.com/questions/12216771/django-objects-for-business-hours
    weekday = models.IntegerField(
        choices=DAYS
    )
    
    from_hour = models.TimeField()
    to_hour = models.TimeField()
    pantry = models.ForeignKey(Pantry, on_delete = models.CASCADE)
    
    def __str__(self):
        return '{0}: From {1} - {2}' .format(self.dayNames[self.weekday-1], self.from_hour.strftime("%I:%M %p"), self.to_hour.strftime("%I:%M %p"))


class Need(models.Model):
    itemName = models.CharField(max_length = 100)
    pantry = models.ForeignKey(Pantry, on_delete = models.CASCADE)
    def __str__(self):
        return '{0}' .format(self.itemName)

class Donor(models.Model):
    name = models.CharField(max_length = 100)

    #https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-phone-number-in-django-models
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list

    email = models.EmailField()

    pantry = models.ForeignKey(Pantry, on_delete = models.CASCADE)
    def __str__(self):
        return 'Name : {0}' .format(self.name)

class Location(models.Model):
    zipCode = models.IntegerField()

    def __str__(self):
      return zipCode


mysite/views.py
from django.shortcuts import render, get_object_or_404, redirect
import re
import sys
from array import *
from .models import Food
from .models import Pantry
from .forms import RegisterForm
from .forms import FoodForm
from .forms import findPantry
from .calc import *
from .forms import *
from django.core.mail import send_mass_mail
from django.http import HttpResponse
from django.contrib.auth import authenticate, login



# Create your views here.
# Use this to pass information to the page you are sending to the client
def mainpage(request):
    return render(request, 'mainpage.html', {})

def inventory(request):
    return render(request, 'inventorypage.html', {})

def pantries(request):
    form = findPantry()
    listedPantries = Pantry.objects.all()
    if str(request).find('=') != -1:
      userZip = str(request)
      userZip = userZip[userZip.rfind('=')+1:-2]
      with  open("zipCodes","r") as conversions:
        for l in conversions:
          if re.search('^' + userZip + '[,]+[^\n]*$', l):
            print(l)
            l = l.split(",")
            userLat = float(l[1].strip())
            userLon = float(l[2].strip())
            print(userLat)
            print(userLon)
            break
      i = 0
      order = [[]]
      with  open("zipCodes","r") as conversions:
        for location in listedPantries:
          for line in conversions:
            if re.search('^' + location.getZipCode() + '[,]+[^\n]*$', line):
              line = line.split(",")
              distance = round(calc_dist_fixed(userLat, userLon, float(line[1].strip()), float(line[2].strip())), 2)
              if i == 0:
                order[i] = [distance, location.name, location.zipCode, location.streetAdd1, location.streetAdd2, location.city, location.state, location.phone_number, location.description, location.websiteURL, location.need_set.all, location.hours_set.all, location.id]
                i += 1
              else:
                order.insert(i, [distance, location.name, location.zipCode, location.streetAdd1, location.streetAdd2, location.city, location.state, location.phone_number, location.description, location.websiteURL, location.need_set.all, location.hours_set.all, location.id])
                i += 1
              conversions.seek(0)
              break
      conversions.close()
      order = bubbleSort(order) #Pass list over to bubbleSort in calc.py to sort by distance
      return render(request, 'findpantrypage.html', {'listedPantries':listedPantries, 'form':form, 'order':order}) #Pass in all pantries as well as zip code and order if available
    else:
      i = 0
      order = [[]]
      for location in listedPantries:
        if i == 0:
          order[i] = ['N/A', location.name, location.zipCode, location.streetAdd1, location.streetAdd2, location.city, location.state, location.phone_number, location.description, location.websiteURL, location.need_set.all, location.hours_set.all, location.id] 
          i += 1
        else:
          order.insert(i, ['N/A', location.name, location.zipCode, location.streetAdd1, location.streetAdd2, location.city, location.state, location.phone_number, location.description, location.websiteURL, location.need_set.all, location.hours_set.all, location.id])
        i += 1
      return render(request, 'findpantrypage.html', {'listedPantries':listedPantries, 'form':form, 'order':order}) #Pass in all pantries as well as zip code and order if available

def add(request):
    return render(request, 'additemspage.html', {})

def remove(request):
    return render(request, 'removeitemspage.html', {})

def display_food(request):
    items = Food.objects.all()
    context = {
        'items' : items,
    }
    return render(request, 'inventorypage.html', context)

def register(response):
   if response.method == "POST":
      form = RegisterForm(response.POST)
      if form.is_valid():
        form.save()
        form = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password1'],)
        login(response, form)
        return redirect("add_pantry")
   else:
      form = RegisterForm()
   return render(response, "register/register.html", {"form":form})

def add_food(request):
    if request.method == "POST":
        data = request.POST.copy()
        form = FoodForm (request.POST)
        #print(form.model)

        if form.is_valid():
            food = Food()
            food.Name = data.get('Name')
            food.Status = data.get('Status')
            food.Amount = data.get('Amount')
            for pantry in request.user.pantry_set.all():
              food.Pantry = pantry
              #just gets first pantry for a user becuase each user should only have one pantry
              break
            food.save()
            return redirect('inventory')
    else:
        form = FoodForm()
        return render(request, 'additemspage.html', {'form': form})

def edit_food(request, pk):
    item = get_object_or_404(Food, pk=pk)

    if request.method == "POST":
        form = FoodForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('inventory')

    else:
        form = FoodForm(instance=item)

        return render(request, 'edit_item.html', {'form': form})
    
def delete_food(request,pk):
    Food.objects.filter(id=pk).delete()
    items = Food.objects.all()
    context = {
        'items':items
    }
    return render(request, 'inventorypage.html', context)

def send_mail_form(request):
    for pantry in request.user.pantry_set.all():
      Donor.pantry = pantry
      #just gets first pantry for a user becuase each user should only have one pantry
      break
    users = Donor.objects.values_list('email', flat=True).filter(pantry=pantry)
    
    
    if request.method == "POST":
        form = mailForm (request.POST)
        subject = request.POST.get('Subject')
        message = request.POST.get('Message')
        if form.is_valid():
            msg1 = (subject, message, 'pantrypalindiana@gmail.com', users )
            send_mass_mail((msg1,))         
            return redirect('inventory')
    else:
        form = mailForm()
        return render(request, 'send_mail.html', {'form': form})
    
def add_pantry(request):
    if request.method == "POST":
      form = PantryForm (request.POST)
      data = request.POST.copy()
      if form.is_valid():
        pantry = Pantry()
        pantry.name = data.get('name')
        pantry.zipCode = data.get('zipCode')
        pantry.streetAdd1 = data.get('streetAdd1')
        pantry.streetAdd2 = data.get('streetAdd2')
        pantry.city = data.get('city')
        pantry.state = data.get('state')
        pantry.phone_number = data.get('phone_number')
        pantry.websiteURL = data.get('websiteURL')
        pantry.description = data.get('description')
        pantry.account = request.user
        pantry.save()
        return redirect('edit_pantry')
    else:
        form = PantryForm()
        return render(request, 'addpantry.html', {'form': form})


def edit_pantry(request):
    pantry = get_object_or_404(request.user.pantry_set)
    if request.method == "POST":
        form = PantryForm(request.POST, instance=pantry)
        if form.is_valid():
            form.save()
            return redirect('inventory')

    else:
        form = PantryForm(instance=pantry)

        return render(request, 'editpantry.html', {'form': form})

def about(request):
    return render(request, 'about.html', {})

def sign_up_form(request):
    if request.method == "POST":
      form = donorForm(request.POST)
      if form.is_valid():
        form.save()
        return redirect('pantries')
    else:
        form = donorForm()
        return render(request, 'donor_sign_up.html', {'form': form})
    
def pantry_inventory(request, pantry_id):
  pantry = get_object_or_404(Pantry, pk=pantry_id)
  context = {
        'pantry' : pantry,
  }
  return render (request, 'pantry_inventory.html', context)

def add_hours(request):
    if request.method == "POST":
        data = request.POST.copy()
        form = HoursForm (request.POST)
        if form.is_valid():
            hours = Hours()
            hours.weekday = data.get('weekday')
            hours.from_hour = data.get('from_hour')
            hours.to_hour = data.get('to_hour')
            for pantry in request.user.pantry_set.all():
              hours.pantry = pantry
              #just gets first pantry for a user becuase each user should only have one pantry
              break
            hours.save()
        return redirect('edit_pantry')
    else:
      form = HoursForm()
      return render(request, 'add_hours.html', {'form': form})

def edit_hours(request, pk):
    hours = get_object_or_404(Hours, pk=pk)

    if request.method == "POST":
        form = HoursForm(request.POST, instance=hours)
        if form.is_valid():
            form.save()
            return redirect('edit_pantry')

    else:
        form = HoursForm(instance=hours)

        return render(request, 'edit_hours.html', {'form': form})
    
def delete_hours(request,pk):
    Hours.objects.filter(id=pk).delete()
    items = Hours.objects.all()
    context = {
        'items':items
    }
    return render(request, 'editpantry.html', context)


def add_need(request):
    if request.method == "POST":
        data = request.POST.copy()
        form = NeedForm (request.POST)
        if form.is_valid():
            need = Need()
            need.itemName = data.get('itemName')
            for pantry in request.user.pantry_set.all():
              need.pantry = pantry
              #just gets first pantry for a user becuase each user should only have one pantry
              break
            need.save()
        return redirect('edit_pantry')
    else:
      form = NeedForm()
      return render(request, 'add_need.html', {'form': form})

    
def delete_need(request,pk):
    Need.objects.filter(id=pk).delete()
    items = Need.objects.all()

mysite/templates/about.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
<style>
    .grid-container{
        display: grid;
        grid-template-columns: 40% 40%;
        grid-gap: 30px 30px;
        padding: 15px;
        justify-content: center;
    }
    .grid-item{
        background-color: lightgray;
        padding:30px;
        text-align: center;
        border-radius: 15px;
    }
    p{
        text-align: left;
    }

</style>
<br><br>
    <h1 style = "text-align: center;">About Us</h1><br><br>
    <div class = "grid-container">
        <div class = "grid-item">
            <h3>How We Did It</h3>
            <p>This project is the result of a five week competition sponsored by Techpoint. We were tasked with developing a tool to help non-profits in Indiana during the current pandemic. We reached out to food pantries in our state to determine what problems they anticipate moving forward and found that many pantries were not taking advantage of the technology available to them. We began listing features that we thought would help local food banks connect and stay organized with the public. From there we sketched out what we wanted the website to look like and began our process of development, testing, and reiteration. Now we are proud to present our solution for Indiana non-profits!
            </p><br>

    </div>
    <div class = "grid-item">
            <h3>The Team</h3>
            <p>
Arvind Krishnan - Sophomore computer engineering student with entrepreneurship at Rose Hulman Institute of Technology<br>
Julia Giddens - Sophomore in Environmental and Ecological Engineering at Purdue<br>
Philip Belpasso - Senior in Computer Information Systems at Ball State University<br>
Sam Vonderahe -  Junior in Computer Science at Purdue<br>
Louis Labuzienski - Junior in Computer Science at Indiana University Bloomington<br>
<br>
We would also like to thank our awesome coaches for helping us along the way and Techpoint for making all of this possible.</p><br>

    </div>

{% endblock %}

mysite/templates/add_hours.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Hours</h1>
    <br>
    <h3>Add Hours</h3>

    <div class = "containter">

    <form method="POST">
      <br>
      {% csrf_token %}
      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        <div class = "col-10">
          {{ field }}
        </div>

      </div>

      {% endfor %}

      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px;"name = "button"> Add Hours </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/add_need.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Needs</h1>
    <br>
    <h3>Add Need</h3>

    <div class = "containter">

    <form method="POST">
      <br>
      {% csrf_token %}
      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        <div class = "col-10">
          {{ field }}
        </div>

      </div>

      {% endfor %}

      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px;"name = "button"> Add Need </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/additemspage.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Inventory</h1>
    <br>
    <h3>Add Items</h3>

    <div class = "containter">

    <form method="POST">
      <br>
      {% csrf_token %}
      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        <div class = "col-10">
          {{ field }}
        </div>

      </div>

      {% endfor %}

      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px;"name = "button"> Add Item </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<!-- Extend this page to display the navigation bar on each page -->
<html>
<head>
<style>
/* This button is for the main buttons on a page
 * Dark blue button that transitions to a gold background on hover
 */
.buttonStyle {
  color: white;
  background-color: #000F5D;
  border-radius: 5px;
  padding: 10px 20px 10px 20px;
}

.buttonStyle:hover {
  background-color: #D59F0F;
  color: #000F5D;
}
/* This button is for minor buttons on a page
 * White button that transitions to dark blue one hover
 */
.onPageButton {
  color: #000F5D;
  border-radius: 5px;
  border-color: #000F5D;
  border-width: 2px;
  border-style: solid;
  padding: 10px 20px 10px 20px;
}

.onPageButton:hover {
  background-color: #000F5D;
  color: white;
}
.divider {
     display: block;
     padding: 10px;
}
</style>
<head>



<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000F5D;">
      {% load static %}
      <img src="{% static "mysite/PantryPal.png" %}" width ="100" height = "100" alt="My image">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="testi collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <div class="divider"></div>
          <li class="nav-item active">
            <a class="nav-link" style="color: white;" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <div class="divider"></div>
          <li class="nav-item">
            <a class="nav-link"  style="color: white;" href="/pantries">Find a Pantry</a>
          </li>
          <div class="divider"></div>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <!-- only shows up when logged in as pantry viewer -->
              <a class="nav-link"  style="color: white;" href="/inventory">Update Inventory</a>
            </li>
            <div class="divider"></div>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link"  style="color: white;" href="/about">About</a>
          </li>
          <div class="divider"></div>
        </ul>
          {% if not user.is_authenticated %}
          <a class="buttonStyle" style="border: 2px solid white; padding: 6px 10px 6px 10px;" href = "/login/">Login</a>
          {% else %}
          <div class = "btn-toolbar">
          <a class="buttonStyle" style="border: 2px solid white; padding: 6px 10px 6px 10px;" href = "/edit_pantry/">Edit Pantry</a>
          <div class="divider"></div>
          <a class="buttonStyle" style="border: 2px solid white; padding: 6px 10px 6px 10px;" href = "/logout/">Logout</a>
          </div>
          {% endif %}
      </div>
    </nav>
{% block body %}


{% endblock %}

mysite/templates/donor_sign_up.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->

{% block body %}
    <h1>Find a Pantry</h1>
    <br>
    <h3>Sign Up</h3>

    <div class = "container">

    <form method="POST">
      <br>
      {% csrf_token %}

      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        
        <div class = "col-10">
          
          {{ field }}
        </div>

      </div>

      {% endfor %}


      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px;"name = "button"> Sign Up </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/edit_hours.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Hours</h1>
    <br>
    <h3>Edit Hours</h3>

    <div class = "containter">

    <form method="POST">
      <br>
      {% csrf_token %}
      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        <div class = "col-10">
          {{ field }}
        </div>

      </div>

      {% endfor %}

      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px; name = "button"> Edit Hours </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/edit_item.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Inventory</h1>
    <br>
    <h3>Edit Items</h3>

    <div class = "containter">

    <form method="POST">
      <br>
      {% csrf_token %}
      {% for field in form %}

      <div class = "form-group row">
        <label for = "id_{{ field.name }}" class = "col-2 col-form-label"> {{ field.label }} </label>
        <div class = "col-10">
          {{ field }}
        </div>

      </div>

      {% endfor %}

      <button type = "submit" class ="buttonStyle" style="padding: 5px 10px 5px 10px; name = "button"> Edit Item </button>
    
    </form>

  </div>

{% endblock %}

mysite/templates/inventorypage.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Inventory</h1><br><br>
    <a class="onPageButton" href = "{% url 'send_mail_form' %}">Send notification to donors</a>
    </br></br></br>
    <a href=  "{% url 'add_food' %}" class="onPageButton" href = "add">Add items</a>
    <a class="onPageButton" href = "#">Import from excel</a>
    <a class="onPageButton" href = "#">Export to excel</a>
    
    <a href=  "{% url 'display_food' %}" class = "buttonStyle" role="button"> Refresh Inventory </a>

    <br><br>

    {% for pantry in user.pantry_set.all %}

    <h4>{{pantry.name}} Inventory</h4>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Amount</th>
            </tr>
        </thead>
    
    <tbody>
    
        {% for item in pantry.food_set.all %}
    
        <tr>
            <td> {{item.Name}} </td>
            <td> {{item.Status}} </td>
            <td> {{item.Amount}} </td>
            <td>
                <a href="{% url  'edit_food' item.pk %}" class = "btn btn-warning btn-sm" role="button"> Edit </a>
                <a href="{% url  'delete_food' item.pk %}" class = "btn btn-danger btn-sm" role="button"> Delete </a>
            </td>
        </tr>
    
        {% endfor %}
    
    </tbody>
    
    </table>
    {% endfor %}

{% endblock %}

mysite/templates/pantry_inventory.html
<!-- This imports the base.html for the naviagation bar-->
{% extends 'base.html' %}


<!-- This is our html that is custom for this specific page-->
{% block body %}
    <h1>Inventory</h1><br><br>
    
    <h4>{{pantry.name}} Inventory</h4>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Amount</th>
            </tr>
        </thead>
    
    <tbody>
    
        {% for item in pantry.food_set.all %}
    
        <tr>
            <td> {{item.Name}} </td>
            <td> {{item.Status}} </td>
            <td> {{item.Amount}} </td>
        </tr>
    
        {% endfor %}
    
    </tbody>
    
    </table>

{% endblock %}